import localFont from "next/font/local";
import {Barlow, Rubik} from "next/font/google"
import "./globals.css";

const barlow = Barlow({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
  display: "swap",
  style: 'normal',
  variable: '--heading-font'
})

const rubik = Rubik({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
  display: "swap",
  style: 'normal',
  variable: '--text-font'
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${barlow.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
